name: AI review by chunks

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  models: read  

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      chunk_count: ${{ steps.diff.outputs.CHUNK_COUNT }}
      chunk_ids_json: ${{ steps.diff.outputs.CHUNK_IDS_JSON }}
      manifest_dir: ${{ steps.diff.outputs.CHUNK_MANIFEST_DIR }}
      diff_all: ${{ steps.diff.outputs.DIFF }}  # optional fallback
      changed_files_all: ${{ steps.diff.outputs.CHANGED_FILES }}
      file_list: ${{ steps.diff.outputs.CHANGED_FILES_FILE }}
      diff_file:      ${{ steps.diff.outputs.DIFF_FILE }}
      context_json: ${{ steps.diff.outputs.CONTEXT }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: diff
        uses: GulerSevil/actions-diff-patch@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pr_number: ${{ github.event.pull_request.number }}
          chunking_enabled: "false"
          max_diff_lines_per_chunk: "0"
          exclude_globs: "**/*.png,**/*.jpg,**/*.xcworkspace/**,**/Pods/**"
          critical_paths_json: '["**/Payments/**","**/Checkout/**","**/OfflineDB/**","**/Printing/**","**/Sync/**","**/Auth/**"]'


  # Removed chunked job for simplicity

  ai:
    needs: prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare inputs as files
        shell: bash
        run: |
          mkdir -p .ai
          printf '%s' "${{ needs.prep.outputs.diff_all }}"          > .ai/diff.all.patch
          printf '%s' "${{ needs.prep.outputs.changed_files_all }}" > .ai/files.all.txt

      - name: AI inference (single)
        id: inference
        uses: actions/ai-inference@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          model: openai/gpt-4o
          prompt-file: .github/prompts/ios-risk-unified.prompt.yml
          input: |
            MODE: pr
            CONTEXT: ${{ needs.prep.outputs.context_json }}
          file_input: |
            FILE_LIST: .ai/files.all.txt
            DIFF:      .ai/diff.all.patch

      - name: Upload response
        uses: actions/upload-artifact@v4
        with:
          name: ai-response
          path: ${{ steps.inference.outputs.response-file }}

