name: PR Risk Analysis

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  models: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  risk_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Calculate delta between base and head of PR
        uses: GulerSevil/actions-diff-patch@v1.3
        id: prepare_diff
        with:
            pr_number: ${{ github.event.pull_request.number }}
            repository: ${{ github.repository }}
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: PR Risk Analysis
        id: risk_analysis
        uses: GulerSevil/action-gh-model-prompt@v1
        with:
            model: gpt-4o
            prompt_path: .github/prompts/ios-risk-unified.prompt
            placeholders_json: >
              {
                "MODE":"pr",
                "DIFF":${{ steps.prepare_diff.outputs.DIFF }},
                "FILE_LIST":${{ steps.prepare_diff.outputs.CHANGED_FILES }},
                "CONTEXT":${{ steps.prepare_diff.outputs.CONTEXT }}
              }
            token: ${{ secrets.GITHUB_TOKEN }}
            response_format: text
            batch_size: 15

      - name: Save report file
        run: |
            printf "%s\n" '${{ steps.risk_analysis.outputs.report }}' > risk-report.md
        
      - name: Upload report artifact
        id: upload_report
        uses: actions/upload-artifact@v4
        with:
            name: risk-report
            path: risk-report.md          

      - name: Comment & gate
        uses: actions/github-script@v7
        with:
              script: |
                const reasons = ${{ toJson(steps.risk_analysis.outputs.message_content) }};
                const url = `${{ steps.upload_report.outputs['artifact-url'] }}`;
                await github.rest.issues.createComment({
                  owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
                  body: `**AI iOS PR Risk:** ${reasons} \n\n [View risk report](${url})`
                });
               
